replicaCount: 1

namespace: default

image:
  repository: mmtxio/mmtx-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 30091

env:
  mmtxPort: "8091"
  storeMode: "file"
  serverNode: "1"